/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#2c2f31",
        "error-container": "#fb5151",
        "surface-container-highest": "#d9dde0",
        "on-tertiary-fixed": "#3e0047",
        "on-error": "#ffefee",
        "on-tertiary": "#ffeefb",
        "inverse-surface": "#0b0f10",
        "tertiary-dim": "#7b2f85",
        "outline-variant": "#abadaf",
        "primary-fixed-dim": "#5391ff",
        "on-primary-fixed-variant": "#002a62",
        "secondary-container": "#c7cfff",
        "on-error-container": "#570008",
        "primary-dim": "#004ca6",
        "tertiary-container": "#f199f7",
        "surface-container-lowest": "#ffffff",
        "error": "#b31b25",
        "background": "#f5f7f9",
        "error-dim": "#9f0519",
        "primary": "#0057bd",
        "surface": "#f5f7f9",
        "surface-dim": "#d0d5d8",
        "on-tertiary-container": "#5e106a",
        "on-tertiary-fixed-variant": "#681c73",
        "on-secondary-fixed": "#00278f",
        "on-surface-variant": "#595c5e",
        "on-secondary-container": "#223ea2",
        "outline": "#747779",
        "surface-container": "#e5e9eb",
        "on-secondary": "#f2f1ff",
        "secondary-fixed": "#c7cfff",
        "tertiary-fixed-dim": "#e28ce9",
        "secondary-fixed-dim": "#b4c1ff",
        "surface-variant": "#d9dde0",
        "surface-container-low": "#eef1f3",
        "on-primary": "#f0f2ff",
        "surface-tint": "#0057bd",
        "on-secondary-fixed-variant": "#2d48ac",
        "on-primary-fixed": "#000000",
        "inverse-primary": "#4d8eff",
        "inverse-on-surface": "#9a9d9f",
        "on-surface": "#2c2f31",
        "surface-bright": "#f5f7f9",
        "primary-container": "#6e9fff",
        "tertiary": "#893c92",
        "secondary": "#3a53b7",
        "surface-container-high": "#dfe3e6",
        "tertiary-fixed": "#f199f7",
        "secondary-dim": "#2c47ab",
        "primary-fixed": "#6e9fff",
        "on-primary-container": "#002150"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
