/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#d6c0f0",
        "on-tertiary-fixed": "#413057",
        "tertiary": "#695781",
        "secondary-fixed": "#dbe2f9",
        "surface-container-high": "#e5e9ec",
        "primary-fixed-dim": "#317bef",
        "inverse-primary": "#4d8eff",
        "surface-variant": "#dee3e7",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#5a6064",
        "secondary-container": "#dbe2f9",
        "on-surface": "#2d3337",
        "primary-dim": "#004fad",
        "on-primary-container": "#000311",
        "on-tertiary-container": "#54436b",
        "primary": "#005bc4",
        "surface-container-low": "#f1f4f7",
        "surface-container-highest": "#dee3e7",
        "surface-tint": "#005bc4",
        "outline-variant": "#adb3b7",
        "on-primary": "#f9f8ff",
        "on-background": "#2d3337",
        "secondary-fixed-dim": "#cdd4eb",
        "inverse-on-surface": "#9b9d9f",
        "primary-fixed": "#4388fd",
        "error-container": "#fa746f",
        "inverse-surface": "#0c0f10",
        "on-tertiary-fixed-variant": "#5e4c75",
        "on-error": "#fff7f6",
        "on-tertiary": "#fef6ff",
        "on-secondary": "#f9f8ff",
        "surface-bright": "#f8f9fb",
        "on-error-container": "#6e0a12",
        "on-secondary-container": "#4a5264",
        "secondary": "#575f72",
        "tertiary-dim": "#5d4b74",
        "on-secondary-fixed": "#383f51",
        "tertiary-fixed": "#e4ceff",
        "on-secondary-fixed-variant": "#545b6e",
        "primary-container": "#4388fd",
        "error": "#a83836",
        "surface-container": "#ebeef1",
        "secondary-dim": "#4b5366",
        "error-dim": "#67040d",
        "surface": "#f8f9fb",
        "surface-dim": "#d5dbdf",
        "on-primary-fixed": "#000000",
        "background": "#f8f9fb",
        "tertiary-container": "#e4ceff",
        "outline": "#767b7f",
        "on-primary-fixed-variant": "#001435"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
